language: go
go:
  - 1.11.x
  

os:
  - linux
  - windows

dist: trusty
sudo: false

install: true

script:
  - env GO111MODULE=on go  build -ldflags "-X main.Version=$TRAVIS_TAG -X main.Hash=$TRAVIS_COMMIT"  github.com/tixu/jiralert/cmd/jiralert
