# Receiver definitions. At least one must be defined.
receivers:
    # Must match the Alertmanager receiver name. Required.
  - name: 'jira-ab'
    # JIRA project to create the issue in. Required.
    project: EA
    # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
    # The type of JIRA issue to create. Required.
    issuetype: Bug
    # Issue priority. Optional.
    priority: Critical
    # Go template invocation for generating the summary. Required.
    summary: '{{ template "jira.alarm.summary" . }}'
    # Go template invocation for generating the description. Optional.
    description: '{{ template "jira.alarm.description" . }}'
    # Go template invocation for generating the comments. Optional.
    comment: '{{ template "jira.alarm.comment" . }}'
    # State to transition into when reopening a closed issue. Required.
    reopenstate: "Reopen Issue"
    # Do not reopen issues with this resolution. Optional.
    wontfixresolution: "Won't Fix"
  # State to transition into when reopening a closed issue. Required.
    addgrouplabels: false
    components: ['Operations']
  
# File containing template definitions. Required.
template: C:\\dev\\go\\src\\github.com\\tixu\\jiralert\\config\\jiralert.tmpl
