# Global defaults, applied to all receivers where not explicitly overridden. Optional.
# 
#  password: 'JIRAlert'
api: 
  # lmkdflmkdlm
  url: https://jira.smals.be
  user: jiralert/config
  password: 'JIRAlert'

# Receiver definitions. At least one must be defined.
receivers:
    # Must match the Alertmanager receiver name. Required.
  - name: 'jira-ab'
    # JIRA project to create the issue in. Required.
    project: AB
    # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
    
    # The type of JIRA issue to create. Required.
    issuetype: Bug
    # Issue priority. Optional.
    priority: Critical
    # Go template invocation for generating the summary. Required.
    summary: '{{ template "jira.summary" . }}'
    # Go template invocation for generating the description. Optional.
    description: '{{ template "jira.description" . }}'
    # State to transition into when reopening a closed issue. Required.
    reopenstate: "To Do"
    # Do not reopen issues with this resolution. Optional.
    wontfixresolution: "Won't Fix"
  # State to transition into when reopening a closed issue. Required.
    reopen_state: "To Do"
    addgrouplabels: false

  
# File containing template definitions. Required.
template: C:\\dev\\go\\src\\github.com\\tixu\\jiralert\\config\\jiralert.yml
